/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication8;

import javax.swing.*;
import java.io.FileWriter;
import java.io.IOException;
/**
 *
 * @author Khaled
 */
public class addStudent extends javax.swing.JFrame {

    /**
     * Creates new form addStudent
     */
    public addStudent() {
        initComponents();
        populateComboBoxes();
    }
    
    private void populateComboBoxes() {
    gender.removeAllItems();
    departement.removeAllItems();

    gender.addItem("Select Gender");
    gender.addItem("Male");
    gender.addItem("Female");

    departement.addItem("Select Department");
    departement.addItem("computer and comunication");
    departement.addItem("electro");
    departement.addItem("megatronics");
    departement.addItem("biomedical");
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        departement = new javax.swing.JComboBox<>();
        savebutton = new javax.swing.JButton();
        textid = new javax.swing.JTextField();
        textname = new javax.swing.JTextField();
        textgpa = new javax.swing.JTextField();
        textage = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("student id");

        jLabel2.setText("student name");

        jLabel3.setText("age");

        jLabel4.setText("gender");

        jLabel5.setText("departemant");

        jLabel6.setText("gpa");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        departement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        departement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departementActionPerformed(evt);
            }
        });

        savebutton.setText("save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        textid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidActionPerformed(evt);
            }
        });

        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });

        textgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textgpaActionPerformed(evt);
            }
        });

        textage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textid)
                            .addComponent(textname)
                            .addComponent(textage)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 133, Short.MAX_VALUE))
                            .addComponent(textgpa)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savebutton)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(departement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(textgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(savebutton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
         String selectedGender = (String) gender.getSelectedItem();
        if (selectedGender != null && selectedGender.equals("Select Gender")) {
    JOptionPane.showMessageDialog(this, "Please select a valid gender.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
    gender.setSelectedIndex(0);
}
    }//GEN-LAST:event_genderActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
       String idText = textid.getText().trim();
    String name = textname.getText().trim();
    String ageText = textage.getText().trim();
    String gpaText = textgpa.getText().trim();
    String genderValue = gender.getSelectedItem().toString();
    String departmentValue = departement.getSelectedItem().toString();

    if (idText.isEmpty() || name.isEmpty() || ageText.isEmpty() || gpaText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "all fields must be filled", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (genderValue.equals("Select Gender")) {
        JOptionPane.showMessageDialog(this, "please select a gender", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (departmentValue.equals("Select Department")) {
        JOptionPane.showMessageDialog(this, "please select a department", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    int id;
    int age;
    double gpa;

    try {
        id = Integer.parseInt(idText);
        age = Integer.parseInt(ageText);
        gpa = Double.parseDouble(gpaText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID, Age, and GPA must be valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (id <= 0) {
        JOptionPane.showMessageDialog(this, "ID must be positive!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!name.matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (age < 10 || age > 100) {
        JOptionPane.showMessageDialog(this, "Age must be between 10 and 100!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (gpa < 0.0 || gpa > 4.0) {
        JOptionPane.showMessageDialog(this, "GPA must be between 0.0 and 4.0!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (FileWriter writer = new FileWriter("students.txt", true)) {
        writer.write(id + "," + name + "," + age + "," + genderValue + "," + departmentValue + "," + gpa + "\n");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving to file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(this, "Student added successfully!");

    textid.setText("");
    textname.setText("");
    textage.setText("");
    textgpa.setText("");
    gender.setSelectedIndex(0);
    departement.setSelectedIndex(0);
    }//GEN-LAST:event_savebuttonActionPerformed

    private void textidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidActionPerformed
         String idText = textid.getText().trim();
    if (!idText.isEmpty()) {
        try {
            int id = Integer.parseInt(idText);
            if (id <= 0) {
                JOptionPane.showMessageDialog(this, "id must be positive", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "id must be a number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_textidActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        String name = textname.getText().trim();
    if (!name.matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_textnameActionPerformed

    private void textageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textageActionPerformed
        String ageText = textage.getText().trim();
    try {
        int age = Integer.parseInt(ageText);
        if (age < 10 || age > 100) {
            JOptionPane.showMessageDialog(this, "Age must be between 10 and 100!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Age must be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_textageActionPerformed

    private void textgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textgpaActionPerformed
        String gpaText = textgpa.getText().trim();
    try {
        double gpa = Double.parseDouble(gpaText);
        if (gpa < 0.0 || gpa > 4.0) {
            JOptionPane.showMessageDialog(this, "gpa must be between 0.0 and 4.0", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "gpa must be a valid number", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_textgpaActionPerformed

    private void departementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departementActionPerformed
        String selectedDepartment = (String) departement.getSelectedItem();
    if (selectedDepartment != null && selectedDepartment.equals("Select Department")) {
        JOptionPane.showMessageDialog(this,"Please select a valid department.","Invalid Input",JOptionPane.WARNING_MESSAGE);
        departement.setSelectedIndex(0);
    } 
    }//GEN-LAST:event_departementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> departement;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField textage;
    private javax.swing.JTextField textgpa;
    private javax.swing.JTextField textid;
    private javax.swing.JTextField textname;
    // End of variables declaration//GEN-END:variables
}
